FROM nginx
FROM node:12

RUN mkdir /web

WORKDIR /web

COPY package*.json ./

# RUN mkdir /etc/nginx/logs && touch /etc/nginx/logs/static.logs
RUN yarn install

COPY . .

# ADD ./nginx.conf /etc/nginx/conf.d/default.conf
# ADD /src /www

ENV PORT=8090
EXPOSE 8090

CMD ["yarn", "build-start"]

