name: Docker Image CI

on:
  push:
    branches: [ nuxt ]
  pull_request:
    branches: [ nuxt ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file DockerFile -t devdefton/portfolio:$(date +%s)
